# Generated by Django 6.0.1 on 2026-02-24 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(default='Somali Early Warning School', max_length=255)),
                ('school_code', models.CharField(default='SEWS-001', max_length=50)),
                ('school_address', models.TextField(default='Mogadishu, Somalia')),
                ('school_phone', models.CharField(default='+252-61-000-0000', max_length=50)),
                ('school_email', models.EmailField(default='info@school.com', max_length=254)),
                ('academic_year', models.CharField(default='2024-2025', max_length=20)),
                ('school_logo', models.ImageField(blank=True, null=True, upload_to='school/')),
                ('absence_threshold', models.IntegerField(default=3)),
                ('auto_escalation_days', models.IntegerField(default=15)),
                ('email_notifications', models.BooleanField(default=True)),
                ('sms_notifications', models.BooleanField(default=False)),
                ('risk_low_min', models.IntegerField(default=0)),
                ('risk_medium_min', models.IntegerField(default=30)),
                ('risk_high_min', models.IntegerField(default=60)),
                ('risk_critical_min', models.IntegerField(default=80)),
                ('session_timeout', models.IntegerField(default=60)),
                ('password_min_length', models.IntegerField(default=8)),
                ('require_uppercase', models.BooleanField(default=True)),
                ('require_numbers', models.BooleanField(default=True)),
                ('data_retention_years', models.IntegerField(default=7)),
                ('two_factor_auth', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
            },
        ),
    ]
