# Generated by Django 5.1.4 on 2026-02-26 20:10

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_two_factor_enabled_user_two_factor_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=core.fields.EncryptedEmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=core.fields.EncryptedCharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=core.fields.EncryptedCharField(blank=True, max_length=50, null=True),
        ),
    ]
