# Generated by Django 6.0.1 on 2026-02-17 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RiskProfile',
            fields=[
                ('risk_profile_id', models.AutoField(primary_key=True, serialize=False)),
                ('risk_score', models.IntegerField(default=0)),
                ('risk_level', models.CharField(max_length=20)),
                ('last_updated', models.DateField(auto_now=True)),
            ],
        ),
    ]
