# Generated by Django 6.0.1 on 2026-02-01 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskProfile',
            fields=[
                ('risk_profile_id', models.AutoField(primary_key=True, serialize=False)),
                ('risk_score', models.IntegerField(default=0)),
                ('risk_level', models.CharField(max_length=20)),
                ('last_updated', models.DateField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
        ),
    ]
