# Generated by Django 6.0.1 on 2026-02-18 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('risk', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentriskprofile',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='risk_profile', to='students.student'),
        ),
        migrations.AddField(
            model_name='subjectriskinsight',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_risk_insights', to='students.student'),
        ),
        migrations.AddField(
            model_name='subjectriskinsight',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_risk_insights', to='academics.subject'),
        ),
        migrations.AddIndex(
            model_name='studentriskprofile',
            index=models.Index(fields=['risk_level'], name='risk_studen_risk_le_610194_idx'),
        ),
        migrations.AddIndex(
            model_name='studentriskprofile',
            index=models.Index(fields=['risk_score'], name='risk_studen_risk_sc_48b7b0_idx'),
        ),
        migrations.AddIndex(
            model_name='subjectriskinsight',
            index=models.Index(fields=['student'], name='risk_subjec_student_99fa6e_idx'),
        ),
        migrations.AddIndex(
            model_name='subjectriskinsight',
            index=models.Index(fields=['subject'], name='risk_subjec_subject_35bcfe_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='subjectriskinsight',
            unique_together={('student', 'subject')},
        ),
    ]
