# Generated by Django 6.0.1 on 2026-02-02 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('risk', '0002_alter_riskprofile_student'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskprofile',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='academics.subject'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='riskprofile',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
        migrations.AlterUniqueTogether(
            name='riskprofile',
            unique_together={('student', 'subject')},
        ),
    ]
