# Generated by Django 6.0.1 on 2026-02-17 16:51

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_initial'),
        ('risk', '0002_initial'),
        ('students', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRiskProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=20)),
                ('last_calculated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='risk_profile', to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectRiskInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_sessions', models.IntegerField(default=0)),
                ('absence_count', models.IntegerField(default=0)),
                ('late_count', models.IntegerField(default=0)),
                ('absence_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('last_calculated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_risk_insights', to='students.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_risk_insights', to='academics.subject')),
            ],
        ),
        migrations.DeleteModel(
            name='RiskProfile',
        ),
        migrations.AddIndex(
            model_name='studentriskprofile',
            index=models.Index(fields=['risk_level'], name='risk_studen_risk_le_610194_idx'),
        ),
        migrations.AddIndex(
            model_name='studentriskprofile',
            index=models.Index(fields=['risk_score'], name='risk_studen_risk_sc_48b7b0_idx'),
        ),
        migrations.AddIndex(
            model_name='subjectriskinsight',
            index=models.Index(fields=['student'], name='risk_subjec_student_99fa6e_idx'),
        ),
        migrations.AddIndex(
            model_name='subjectriskinsight',
            index=models.Index(fields=['subject'], name='risk_subjec_subject_35bcfe_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='subjectriskinsight',
            unique_together={('student', 'subject')},
        ),
    ]
