# Generated by Django 6.0.1 on 2026-03-23 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0004_subjectriskinsight_day_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentriskprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='subjectriskinsight',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
