# Generated by Django 6.0.1 on 2026-02-01 14:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CounsellingSession',
            fields=[
                ('session_id', models.AutoField(primary_key=True, serialize=False)),
                ('session_date', models.DateField()),
                ('issues_identified', models.TextField()),
                ('notes', models.TextField()),
                ('counsellor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
        ),
    ]
