# Generated by Django 6.0.1 on 2026-02-17 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CounsellingSession',
            fields=[
                ('session_id', models.AutoField(primary_key=True, serialize=False)),
                ('session_date', models.DateField()),
                ('issues_identified', models.TextField()),
                ('notes', models.TextField()),
                ('progress_status', models.CharField(choices=[('in_progress', 'In Progress'), ('improving', 'Improving'), ('not_improving', 'Not Improving')], default='in_progress', max_length=20)),
                ('admin_notified', models.BooleanField(default=False)),
            ],
        ),
    ]
