# Generated by Django 6.0.1 on 2026-02-02 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='counsellingsession',
            name='admin_notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='counsellingsession',
            name='progress_status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('improving', 'Improving'), ('not_improving', 'Not Improving')], default='in_progress', max_length=20),
        ),
    ]
