# Generated by Django 6.0.1 on 2026-02-02 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('counselling', '0002_counsellingsession_admin_notified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='counsellingsession',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='academics.subject'),
            preserve_default=False,
        ),
    ]
