# Generated by Django 6.0.1 on 2026-02-18 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterventionCase',
            fields=[
                ('case_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('awaiting_parent', 'Awaiting Parent Meeting'), ('escalated_to_admin', 'Escalated to Admin'), ('closed', 'Closed')], default='open', max_length=30)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('outcome_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases', to='alerts.alert')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
