# Generated by Django 6.0.1 on 2026-02-17 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('intervention_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('due_date', models.DateField()),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interventions', to='alerts.alert')),
            ],
        ),
    ]
