# Generated by Django 6.0.1 on 2026-02-01 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('counselling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('intervention_id', models.AutoField(primary_key=True, serialize=False)),
                ('action_taken', models.TextField()),
                ('follow_up_date', models.DateField()),
                ('status', models.CharField(max_length=20)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='counselling.counsellingsession')),
            ],
        ),
    ]
