# Generated by Django 6.0.1 on 2026-02-24 13:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('interventions', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='interventioncase',
            name='assigned_to',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'form_master'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_cases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='interventioncase',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intervention_cases', to='students.student'),
        ),
        migrations.AddField(
            model_name='interventionmeeting',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_meetings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='interventionmeeting',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intervention_meetings', to='students.student'),
        ),
        migrations.AddField(
            model_name='progressupdate',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='progressupdate',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_updates', to='interventions.interventionmeeting'),
        ),
        migrations.AddIndex(
            model_name='interventioncase',
            index=models.Index(fields=['status'], name='interventio_status_2704f8_idx'),
        ),
        migrations.AddIndex(
            model_name='interventioncase',
            index=models.Index(fields=['assigned_to'], name='interventio_assigne_2012c9_idx'),
        ),
        migrations.AddIndex(
            model_name='interventionmeeting',
            index=models.Index(fields=['student', 'status'], name='interventio_student_2ddbab_idx'),
        ),
        migrations.AddIndex(
            model_name='interventionmeeting',
            index=models.Index(fields=['status'], name='interventio_status_147047_idx'),
        ),
        migrations.AddIndex(
            model_name='interventionmeeting',
            index=models.Index(fields=['urgency_level'], name='interventio_urgency_b169d7_idx'),
        ),
    ]
