# Generated by Django 6.0.1 on 2026-02-17 09:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0003_initial'),
        ('counselling', '0002_initial'),
        ('interventions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='intervention',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_interventions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='intervention',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='counselling.counsellingsession'),
        ),
        migrations.AddField(
            model_name='intervention',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.subject'),
        ),
    ]
