# Generated by Django 6.0.1 on 2026-02-02 06:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interventions', '0002_rename_action_taken_intervention_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intervention',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='intervention',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_interventions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
