# Generated by Django 6.0.1 on 2026-02-18 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interventions', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interventioncase',
            name='resolution_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
