# Generated by Django 6.0.1 on 2026-02-20 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interventions', '0003_interventioncase_resolution_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='interventioncase',
            name='meeting_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interventioncase',
            name='meeting_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interventioncase',
            name='progress_status',
            field=models.CharField(choices=[('no_contact', 'No Contact Yet'), ('contacted', 'Student Contacted'), ('improving', 'Showing Improvement'), ('not_improving', 'Not Improving'), ('resolved', 'Issue Resolved')], default='no_contact', max_length=20),
        ),
    ]
