# Generated by Django 6.0.1 on 2026-02-02 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('alerts', '0002_alert_subject_alter_alert_alert_type'),
        ('interventions', '0003_remove_intervention_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervention',
            name='alert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interventions', to='alerts.alert'),
        ),
        migrations.AddField(
            model_name='intervention',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='academics.subject'),
            preserve_default=False,
        ),
    ]
