# Generated by Django 6.0.1 on 2026-02-20 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interventions', '0004_interventioncase_meeting_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interventioncase',
            name='escalation_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
