# Generated by Django 6.0.1 on 2026-03-23 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interventions', '0004_alter_interventionmeeting_id_alter_progressupdate_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='interventioncase',
            name='attendance_rate_at_close',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Student attendance rate (%) when this case was closed', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='interventioncase',
            name='attendance_rate_at_open',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Student attendance rate (%) when this case was opened', max_digits=5, null=True),
        ),
    ]
