# Generated by Django 6.0.1 on 2026-02-21 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interventions', '0008_intervention_meeting_and_progress'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='interventioncase',
            name='case_assigned_idx',
        ),
        migrations.RemoveIndex(
            model_name='interventioncase',
            name='case_student_idx',
        ),
        migrations.RemoveIndex(
            model_name='interventioncase',
            name='case_progress_idx',
        ),
        migrations.RenameIndex(
            model_name='interventionmeeting',
            new_name='interventio_student_2ddbab_idx',
            old_name='interventio_student_idx',
        ),
        migrations.RenameIndex(
            model_name='interventionmeeting',
            new_name='interventio_status_147047_idx',
            old_name='interventio_status_idx',
        ),
        migrations.RenameIndex(
            model_name='interventionmeeting',
            new_name='interventio_urgency_b169d7_idx',
            old_name='interventio_urgency_idx',
        ),
    ]
