# Generated by Django 6.0.1 on 2026-03-17 20:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_initial'),
        ('students', '0004_student_parent_email_student_parent_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceScheduleView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday')], max_length=10)),
                ('period', models.CharField(choices=[('1', 'Period 1 (8:00-8:45)'), ('2', 'Period 2 (8:45-9:30)'), ('3', 'Period 3 (9:45-10:30)'), ('4', 'Period 4 (10:30-11:15)'), ('5', 'Period 5 (11:30-12:15)'), ('6', 'Period 6 (12:15-1:00)'), ('7', 'Period 7 (2:00-2:45)')], max_length=2)),
                ('is_completed_today', models.BooleanField(default=False)),
                ('last_attendance_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'attendance_schedule_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TimetableTemplate',
            fields=[
                ('template_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="e.g., 'Grade 10 Science Track', 'Grade 12 Arts Track'", max_length=100)),
                ('description', models.TextField(blank=True)),
                ('target_grade', models.CharField(help_text="e.g., 'Grade 10', 'Form 4'", max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(limit_choices_to={'role': 'admin'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['target_grade', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SchoolTimetable',
            fields=[
                ('timetable_id', models.AutoField(primary_key=True, serialize=False)),
                ('academic_year', models.CharField(help_text='e.g., 2024-2025', max_length=20)),
                ('term', models.CharField(help_text='e.g., Term 1, Semester 1', max_length=20)),
                ('day_of_week', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday')], max_length=10)),
                ('period', models.CharField(choices=[('1', 'Period 1 (8:00-8:45)'), ('2', 'Period 2 (8:45-9:30)'), ('3', 'Period 3 (9:45-10:30)'), ('4', 'Period 4 (10:30-11:15)'), ('5', 'Period 5 (11:30-12:15)'), ('6', 'Period 6 (12:15-1:00)'), ('7', 'Period 7 (2:00-2:45)')], max_length=2)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='students.classroom')),
                ('created_by', models.ForeignKey(limit_choices_to={'role': 'admin'}, on_delete=django.db.models.deletion.CASCADE, related_name='created_timetables', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_slots', to='academics.subject')),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='timetable_slots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['classroom', 'day_of_week', 'period'],
                'indexes': [models.Index(fields=['classroom', 'day_of_week'], name='academics_s_classro_2e6ea3_idx'), models.Index(fields=['teacher', 'day_of_week'], name='academics_s_teacher_7c6d9a_idx')],
                'unique_together': {('classroom', 'day_of_week', 'period'), ('teacher', 'day_of_week', 'period')},
            },
        ),
        migrations.CreateModel(
            name='TimetableTemplateSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday')], max_length=10)),
                ('period', models.CharField(choices=[('1', 'Period 1 (8:00-8:45)'), ('2', 'Period 2 (8:45-9:30)'), ('3', 'Period 3 (9:45-10:30)'), ('4', 'Period 4 (10:30-11:15)'), ('5', 'Period 5 (11:30-12:15)'), ('6', 'Period 6 (12:15-1:00)'), ('7', 'Period 7 (2:00-2:45)')], max_length=2)),
                ('preferred_teacher', models.ForeignKey(blank=True, limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.subject')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='academics.timetabletemplate')),
            ],
            options={
                'ordering': ['day_of_week', 'period'],
                'unique_together': {('template', 'day_of_week', 'period')},
            },
        ),
    ]
