# Generated by Django 6.0.1 on 2026-02-20 08:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_subject_code_teachingassignment_is_active_and_more'),
        ('students', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teachingassignment',
            unique_together={('teacher', 'subject', 'classroom')},
        ),
        migrations.AlterField(
            model_name='teachingassignment',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Admin can deactivate without deleting'),
        ),
        migrations.RemoveField(
            model_name='teachingassignment',
            name='academic_term',
        ),
        migrations.DeleteModel(
            name='AcademicTerm',
        ),
    ]
