# Generated by Django 6.0.1 on 2026-03-23 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_add_subject_scheduling_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schooltimetable',
            name='period',
            field=models.CharField(choices=[('1', 'Period 1 (8:00-8:45)'), ('2', 'Period 2 (8:45-9:30)'), ('3', 'Period 3 (9:30-10:15)'), ('4', 'Period 4 (11:00-11:45)'), ('5', 'Period 5 (11:45-12:30)'), ('6', 'Period 6 (12:30-1:15)')], max_length=2),
        ),
        migrations.AlterField(
            model_name='timetabletemplateslot',
            name='period',
            field=models.CharField(choices=[('1', 'Period 1 (8:00-8:45)'), ('2', 'Period 2 (8:45-9:30)'), ('3', 'Period 3 (9:30-10:15)'), ('4', 'Period 4 (11:00-11:45)'), ('5', 'Period 5 (11:45-12:30)'), ('6', 'Period 6 (12:30-1:15)')], max_length=2),
        ),
    ]
