# Generated by Django 5.1.4 on 2026-02-26 11:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_initial'),
        ('attendance', '0003_initial'),
        ('students', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceSessionArchive',
            fields=[
                ('session_id', models.AutoField(primary_key=True, serialize=False)),
                ('attendance_date', models.DateField(db_index=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archived_sessions', to='students.classroom')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archived_sessions', to='academics.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archived_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'attendance_session_archive',
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecordArchive',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('excused', 'Excused')], max_length=10)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archived_attendance_records', to='students.student')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='attendance.attendancesessionarchive')),
            ],
            options={
                'db_table': 'attendance_record_archive',
            },
        ),
        migrations.AddIndex(
            model_name='attendancesessionarchive',
            index=models.Index(fields=['attendance_date'], name='attendance__attenda_9f93be_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancerecordarchive',
            index=models.Index(fields=['student'], name='attendance__student_08ae22_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancerecordarchive',
            index=models.Index(fields=['status'], name='attendance__status_05b1f4_idx'),
        ),
    ]
