# Generated by Django 5.1.4 on 2026-03-10 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_attendance_improvements'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='attendanceaudit',
            new_name='attendance__record__b77806_idx',
            old_name='attendance_audit_record_changed_idx',
        ),
        migrations.RenameIndex(
            model_name='attendanceaudit',
            new_name='attendance__changed_530cc5_idx',
            old_name='attendance_audit_changed_by_idx',
        ),
        migrations.RenameIndex(
            model_name='attendancerecord',
            new_name='attendance__marked__aa864c_idx',
            old_name='attendance_record_marked_at_idx',
        ),
        migrations.RenameIndex(
            model_name='attendancesession',
            new_name='attendance__recorde_cd99da_idx',
            old_name='attendance_session_recorded_at_idx',
        ),
    ]
