# Generated by Django 6.0.1 on 2026-02-17 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('alert_id', models.AutoField(primary_key=True, serialize=False)),
                ('alert_type', models.CharField(max_length=100)),
                ('alert_date', models.DateField(auto_now_add=True)),
                ('risk_level', models.CharField(max_length=20)),
                ('status', models.CharField(default='active', max_length=20)),
            ],
        ),
    ]
