# Generated by Django 6.0.1 on 2026-02-22 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_add_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='alert',
            name='alert_assigned_idx',
        ),
        migrations.RemoveIndex(
            model_name='alert',
            name='alert_student_idx',
        ),
    ]
