# Generated by Django 6.0.1 on 2026-02-18 06:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_initial'),
        ('alerts', '0004_alter_alert_status'),
        ('students', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='assigned_to',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'form_master'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alert',
            name='escalated_to_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['assigned_to'], name='alerts_aler_assigne_24f8e3_idx'),
        ),
    ]
