# Generated by Django 6.0.1 on 2026-02-01 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('class_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=120)),
                ('class_level', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=10)),
                ('status', models.CharField(default='active', max_length=20)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.classroom')),
            ],
        ),
    ]
