# Generated by Django 5.1.4 on 2026-02-26 20:10

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='full_name',
            field=core.fields.EncryptedCharField(max_length=255),
        ),
    ]
