# Generated by Django 6.0.1 on 2026-03-23 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_student_parent_email_student_parent_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='chronic_absentee',
            field=models.BooleanField(default=False, help_text='True when student has had 3+ closed cases — triggers auto-escalation on next case'),
        ),
        migrations.AddField(
            model_name='student',
            name='intervention_count',
            field=models.PositiveIntegerField(default=0, help_text='Total number of closed intervention cases for this student'),
        ),
        migrations.AddField(
            model_name='student',
            name='persistent_absentee',
            field=models.BooleanField(default=False, help_text='True when attendance rate falls below 90% (UK DfE standard)'),
        ),
    ]
