"""
Professional Email Notification Service for School Early Warning System
Sends comprehensive attendance alerts with detailed absence information
"""
from django.core.mail import send_mail, EmailMultiAlternatives
from django.conf import settings
from django.utils import timezone
from django.template.loader import render_to_string
from datetime import datetime, timedelta
import logging

logger = logging.getLogger(__name__)


def get_email_sender(form_master=None):
    """
    Determine email sender based on configuration
    """
    sender_type = getattr(settings, 'EMAIL_SENDER_TYPE', 'form_master')
    
    if sender_type == 'form_master' and form_master:
        return f"{form_master.name} <{form_master.email}>"
    elif sender_type == 'principal':
        principal_name = getattr(settings, 'SCHOOL_PRINCIPAL_NAME', 'Principal')
        principal_email = getattr(settings, 'SCHOOL_PRINCIPAL_EMAIL', settings.DEFAULT_FROM_EMAIL)
        return f"{principal_name} <{principal_email}>"
    else:  # 'school' or fallback
        school_name = getattr(settings, 'SCHOOL_NAME', 'School Administration')
        return f"{school_name} <{settings.DEFAULT_FROM_EMAIL}>"


def get_email_signature(form_master=None):
    """
    Get appropriate email signature based on sender type
    """
    sender_type = getattr(settings, 'EMAIL_SENDER_TYPE', 'form_master')
    school_name = getattr(settings, 'SCHOOL_NAME', 'School Administration')
    
    if sender_type == 'form_master' and form_master:
        enrollment = getattr(form_master, 'managed_classroom', None)
        classroom_name = enrollment.name if enrollment else 'Unknown Class'
        return f"""{form_master.name}
Form Master, {classroom_name}
{school_name}"""
    elif sender_type == 'principal':
        principal_name = getattr(settings, 'SCHOOL_PRINCIPAL_NAME', 'Principal')
        return f"""{principal_name}
Principal
{school_name}"""
    else:  # 'school'
        return f"""{school_name}
School Early Warning System"""


def send_absence_alert(student, consecutive_days, subject_name=None):
    """
    PROFESSIONAL: Send detailed absence alert with complete absence history
    Recipients: Parent + Form Master + Admin (if critical)
    """
    try:
        # Get detailed absence information
        absence_details = get_student_absence_details(student, subject_name)
        
        # Get form master from active enrollment
        enrollment = student.enrollments.filter(is_active=True).first()
        if not enrollment or not enrollment.classroom.form_master:
            logger.warning(f"No form master found for student {student.student_id}")
            return
        
        form_master = enrollment.classroom.form_master
        
        # Determine alert severity
        alert_level = "CRITICAL" if consecutive_days >= 5 else "HIGH" if consecutive_days >= 3 else "MEDIUM"
        
        # PROFESSIONAL EMAIL TO PARENT
        if student.parent_email:
            parent_subject = f"URGENT: Attendance Alert - {student.full_name} ({alert_level} PRIORITY)"
            
            # Get sender and signature
            sender_email = get_email_sender(form_master)
            signature = get_email_signature(form_master)
            
            parent_message = f"""
Dear {student.parent_name or 'Parent/Guardian'},

RE: URGENT ATTENDANCE ALERT - {student.full_name}
Student ID: {student.admission_number}
Class: {enrollment.classroom.name}
Alert Level: {alert_level}
Date: {timezone.now().strftime('%B %d, %Y')}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

ABSENCE SUMMARY:
• Consecutive Absences: {consecutive_days} days
• Subject Affected: {subject_name or 'Multiple Subjects'}
• Total Absences This Month: {absence_details['monthly_absences']} days
• Attendance Rate: {absence_details['attendance_rate']:.1f}%

DETAILED ABSENCE RECORD:
{format_absence_history(absence_details['recent_absences'])}

SUBJECTS AFFECTED:
{format_subject_absences(absence_details['subject_breakdown'])}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

IMMEDIATE ACTION REQUIRED:
1. Please contact me immediately to explain the absences
2. Provide medical certificates if absences are health-related
3. Schedule a meeting with me to discuss support strategies
4. Ensure regular attendance moving forward

ACADEMIC IMPACT:
Regular attendance is crucial for academic success. Extended absences may result in:
• Difficulty catching up with coursework
• Lower academic performance
• Potential intervention measures
• Administrative review if pattern continues

CONTACT INFORMATION:
Form Master: {form_master.name}
Email: {form_master.email}
School Phone: {getattr(settings, 'SCHOOL_PHONE', 'Contact School')}

Please respond to this email or contact me within 24 hours.

This alert was generated by our School Early Warning System to ensure your child receives the support they need.

Sincerely,
{signature}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
This email was sent on {timezone.now().strftime('%B %d, %Y at %I:%M %p')}
For technical issues, contact: {getattr(settings, 'TECH_SUPPORT_EMAIL', 'support@school.edu')}
"""
            
            send_mail(
                subject=parent_subject,
                message=parent_message,
                from_email=sender_email,
                recipient_list=[student.parent_email],
                fail_silently=False,
            )
            logger.info(f"Professional absence alert sent to parent: {student.parent_email}")
        
        # PROFESSIONAL EMAIL TO FORM MASTER
        form_master_subject = f"Student Absence Alert: {student.full_name} - {consecutive_days} Days ({alert_level})"
        
        form_master_message = f"""
Dear {form_master.name},

RE: STUDENT ABSENCE ALERT - IMMEDIATE ATTENTION REQUIRED
Student: {student.full_name} (ID: {student.admission_number})
Class: {enrollment.classroom.name}
Alert Level: {alert_level}
Generated: {timezone.now().strftime('%B %d, %Y at %I:%M %p')}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

ABSENCE ANALYTICS:
• Consecutive Absences: {consecutive_days} days
• Subject: {subject_name or 'Multiple Subjects'}
• Monthly Total: {absence_details['monthly_absences']} absences
• Attendance Rate: {absence_details['attendance_rate']:.1f}%
• Risk Level: {get_risk_level(absence_details['attendance_rate'])}

RECENT ABSENCE PATTERN:
{format_absence_history(absence_details['recent_absences'])}

SUBJECT-WISE BREAKDOWN:
{format_subject_absences(absence_details['subject_breakdown'])}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

RECOMMENDED ACTIONS:
1. Contact parent immediately (email sent automatically)
2. Review student's academic performance in affected subjects
3. Consider peer support or buddy system
4. Schedule intervention meeting if pattern continues
5. Document all communication and actions taken

SYSTEM RECOMMENDATIONS:
{get_intervention_recommendations(consecutive_days, absence_details['attendance_rate'])}

ACCESS DASHBOARD:
View detailed analytics: {getattr(settings, 'FRONTEND_URL', 'https://school.edu')}/form-master/dashboard
Student Profile: {getattr(settings, 'FRONTEND_URL', 'https://school.edu')}/form-master/students/{student.student_id}

This alert was generated by the Early Warning System based on attendance patterns.
Please take appropriate action and update the system with your interventions.

Best regards,
School Early Warning System
"""
        
        send_mail(
            subject=form_master_subject,
            message=form_master_message,
            from_email=settings.DEFAULT_FROM_EMAIL,
            recipient_list=[form_master.email],
            fail_silently=False,
        )
        logger.info(f"Professional absence alert sent to form master: {form_master.email}")
        
        # CRITICAL ALERT TO ADMIN (if 5+ consecutive days)
        if consecutive_days >= 5:
            send_critical_absence_alert_to_admin(student, consecutive_days, absence_details)
        
    except Exception as e:
        logger.error(f"Failed to send professional absence alert for student {student.student_id}: {e}")
        raise  # Re-raise for capstone project - no silent failures


def get_student_absence_details(student, subject_name=None):
    """Get comprehensive absence details for professional reporting"""
    from attendance.models import AttendanceRecord
    
    records = AttendanceRecord.objects.filter(
        student=student
    ).select_related('session__subject', 'session').order_by('-session__attendance_date')
    
    thirty_days_ago = timezone.now().date() - timedelta(days=30)
    monthly_records = records.filter(session__attendance_date__gte=thirty_days_ago)
    monthly_absences = monthly_records.filter(status='absent').count()
    total_monthly_sessions = monthly_records.count()
    
    attendance_rate = 0
    if total_monthly_sessions > 0:
        present_sessions = monthly_records.filter(status='present').count()
        attendance_rate = (present_sessions / total_monthly_sessions) * 100
    
    recent_absences = []
    for record in records[:10]:
        if record.status in ['absent', 'late']:
            recent_absences.append({
                'date': record.session.attendance_date,
                'subject': record.session.subject.name,
                'status': record.status,
                'remarks': record.remarks or ''
            })
    
    subject_breakdown = {}
    for record in records.filter(status='absent')[:20]:
        subject = record.session.subject.name
        if subject not in subject_breakdown:
            subject_breakdown[subject] = {'count': 0, 'dates': []}
        subject_breakdown[subject]['count'] += 1
        subject_breakdown[subject]['dates'].append(record.session.attendance_date)
    
    return {
        'monthly_absences': monthly_absences,
        'attendance_rate': attendance_rate,
        'recent_absences': recent_absences,
        'subject_breakdown': subject_breakdown
    }


def format_absence_history(recent_absences):
    """Format recent absence history for email display"""
    if not recent_absences:
        return "No recent absences recorded."
    
    formatted = []
    for absence in recent_absences[:7]:
        date_str = absence['date'].strftime('%B %d, %Y (%A)')
        status_icon = "X" if absence['status'] == 'absent' else "LATE"
        remarks = f" - {absence['remarks']}" if absence['remarks'] else ""
        formatted.append(f"  {status_icon} {date_str} | {absence['subject']}{remarks}")
    
    return "\n".join(formatted)


def format_subject_absences(subject_breakdown):
    """Format subject-wise absence breakdown"""
    if not subject_breakdown:
        return "No subject-specific data available."
    
    formatted = []
    for subject, data in sorted(subject_breakdown.items(), key=lambda x: x[1]['count'], reverse=True):
        recent_dates = sorted(data['dates'], reverse=True)[:3]
        date_str = ", ".join([d.strftime('%m/%d') for d in recent_dates])
        formatted.append(f"  {subject}: {data['count']} absences (Recent: {date_str})")
    
    return "\n".join(formatted)


def get_risk_level(attendance_rate):
    """Determine risk level based on attendance rate"""
    if attendance_rate >= 95:
        return "LOW RISK"
    elif attendance_rate >= 85:
        return "MEDIUM RISK"
    elif attendance_rate >= 75:
        return "HIGH RISK"
    else:
        return "CRITICAL RISK"


def get_intervention_recommendations(consecutive_days, attendance_rate):
    """Get specific intervention recommendations"""
    recommendations = []
    
    if consecutive_days >= 5:
        recommendations.append("• IMMEDIATE: Schedule parent meeting within 24 hours")
        recommendations.append("• URGENT: Request medical documentation if health-related")
        recommendations.append("• CRITICAL: Consider home visit or welfare check")
    
    if attendance_rate < 75:
        recommendations.append("• Academic: Arrange catch-up sessions with subject teachers")
        recommendations.append("• Support: Assign peer mentor or study buddy")
        recommendations.append("• Monitoring: Daily attendance check-ins")
    
    if consecutive_days >= 3:
        recommendations.append("• Communication: Daily parent contact until pattern improves")
        recommendations.append("• Documentation: Record all interventions in student file")
    
    return "\n".join(recommendations) if recommendations else "• Standard monitoring and support protocols"


def send_critical_absence_alert_to_admin(student, consecutive_days, absence_details):
    """Send critical alert to administrators for severe cases"""
    try:
        from users.models import User
        
        admins = User.objects.filter(role='admin', is_active=True)
        admin_emails = [admin.email for admin in admins]
        
        if not admin_emails:
            logger.warning("No active administrators found for critical alert")
            return
        
        enrollment = student.enrollments.filter(is_active=True).first()
        
        subject = f"CRITICAL ABSENCE ALERT: {student.full_name} - {consecutive_days} Consecutive Days"
        
        message = f"""
CRITICAL ABSENCE ALERT - ADMINISTRATIVE INTERVENTION REQUIRED

Student: {student.full_name}
ID: {student.admission_number}
Class: {enrollment.classroom.name if enrollment else 'Unknown'}
Form Master: {enrollment.classroom.form_master.name if enrollment and enrollment.classroom.form_master else 'Unassigned'}

CRITICAL METRICS:
• Consecutive Absences: {consecutive_days} days
• Monthly Absences: {absence_details['monthly_absences']} days
• Attendance Rate: {absence_details['attendance_rate']:.1f}%
• Risk Level: {get_risk_level(absence_details['attendance_rate'])}

IMMEDIATE ADMINISTRATIVE ACTION REQUIRED:
1. Review case for potential child welfare concerns
2. Authorize home visit if necessary
3. Consider involving social services
4. Review school attendance policies and consequences
5. Schedule administrative meeting with parents

This alert requires immediate attention due to the severity of the absence pattern.

Access Admin Dashboard: {getattr(settings, 'FRONTEND_URL', 'https://school.edu')}/admin/dashboard

School Early Warning System
Generated: {timezone.now().strftime('%B %d, %Y at %I:%M %p')}
"""
        
        send_mail(
            subject=subject,
            message=message,
            from_email=settings.DEFAULT_FROM_EMAIL,
            recipient_list=admin_emails,
            fail_silently=False,
        )
        
        logger.info(f"Critical absence alert sent to {len(admin_emails)} administrators")
        
    except Exception as e:
        logger.error(f"Failed to send critical absence alert to admin: {e}")


# Keep existing functions for compatibility
def send_alert_notification(alert):
    """Send email when high-risk alert is created"""
    pass

def send_case_escalation_notification(case):
    """Send email when case is escalated to admin"""
    pass

def send_case_resolved_notification(case):
    """Send email when case is successfully resolved"""
    pass